### ISSUE TITLE
Backend: Mantenimiento de mapas

### ISSUE THREAD

**Issue by avozme** [SergioMorenoAntequera/CeliaMaps#5]
CRUD de la tabla de mapas. Al subir un mapa, quizá sea conveniente crear una miniatura para manejar la miniatura en algunas vistas, en lugar del mapa completo.

Debe permitirse reordenar los mapas con facilidad (¿drag&drop?) y marcar uno como principal (generalmente, será el más moderno)

También debe permitirse alinear los mapas, ya que los mapas más antiguos serán más pequeños.

**Comment by SergioMorenoAntequera** [comment]
Que hacer:
  -> Hacer lo de las flechas para subir y bajar el nivel de los mapas
  -> Que al insertar un mapa se puedan alinear con el superior
  -> Si no se alinea los mapas que no puedas pasar al insertar calles y que se te salte un aviso de que tienes que alinearlo en el index si decides guardarlo sin alinear
  -> Poner un boton para alinear por si acaso queremos alinearlo más tarde
